<h1 style="text-align: center; color: #091A2B; font-size: 36px; font-weight: bold;">
    🏘️ LensEstate — An End-to-End Real Estate Analytics Engine
</h1>
<hr style="height: 2px; border: none; background-color: #ffffff;">

<h1 style=" color: #426d84; font-size: 32px; font-weight: bold;">
    🧭 1. Introduction
</h1>

<p> The Tunisian real estate market is characterized by fragmented information, informal practices, and limited analytical transparency, making reliable property valuation and market analysis difficult for both individuals and institutions. Despite the growing volume of digital listings and online activity, most available information remains unstructured, inconsistent, and disconnected from broader economic and regional dynamics.

This project introduces TuniEstate, an AI-powered intelligent system designed to transform dispersed real estate data into structured knowledge and actionable insights. The platform aims to integrate heterogeneous data sources, apply advanced analytical models, and provide predictive and decision-support capabilities adapted to the Tunisian socio-economic context.

By combining automated data acquisition, multi-modal analysis, forecasting mechanisms, and conversational interaction, TuniEstate seeks to bridge the gap between raw market information and informed decision-making. The system aspires to enhance transparency, reduce information asymmetry, and democratize access to real estate intelligence for a wide range of stakeholders. </p>

<h2 style="color: #7b98a6;" > 🛠️ Planning:</h2>
<ul>
    <li>🔍 Data Understanding</li>
    <li>🧭 Data Exploration</li>
    <li>📊 Data Preparation</li>
    <li>🤖 Modeling</li>
    <li>⚖️ Model Comparison</li>
    <li>🚀 Deployement</li>
    <li>⚖️ Conclusion</li>
    
</ul>

mubaweb

In [1]:
import pandas as pd
import glob

# Get all CSV file paths
mubaweb_files = glob.glob("Data/raw_listings/mubaweb/*.csv")

# Read and combine them into one DataFrame
mubaweb_df = pd.concat(
    (pd.read_csv(file) for file in mubaweb_files),
    ignore_index=True
)

# Check the result
mubaweb_df.head()

,listing_id,listing_url,source,title,property_type,transaction_type,price,currency,price_type,surface_m2,...,has_chauffage,has_climatisation,has_jardin,has_meuble,has_parking,has_piscine,has_securite,has_standing,has_terrasse,has_vue_mer
0,7836763,https://www.mubawab.tn/fr/a/7836763/a-vendre-v...,mubawab,A vendre villa jumelee a mourouj 3,Villa,à vendre,320000.0,TND,fixed,NaN,...,False,False,False,False,True,False,False,True,True,False
1,8187888,https://www.mubawab.tn/fr/a/8187888/charmant-d...,mubawab,"Charmant Duplex à Ain Zaghouan, Tunis 200m²",NaN,à vendre,600000.0,TND,fixed,200.0,...,False,True,True,False,True,False,False,False,True,False
2,8187887,https://www.mubawab.tn/fr/a/8187887/duplex-s3-...,mubawab,Duplex S3 à Ain Zaghouan Nord,NaN,à vendre,520000.0,TND,fixed,NaN,...,False,False,True,False,False,False,False,False,True,False
3,8080588,https://www.mubawab.tn/fr/a/8080588/superbe-fe...,mubawab,Superbe Ferme en pleine activité à Soliman,Ferme,à vendre,990000.0,TND,fixed,NaN,...,False,True,False,False,True,False,True,False,False,False
4,8201548,https://www.mubawab.tn/fr/a/8201548/ferme-zaid...,mubawab,Ferme Zaido à Vendre à Hydra Kasserine,Ferme,à vendre,2000000.0,TND,fixed,240.0,...,False,True,False,False,False,False,False,False,False,False

In [2]:
print("number of lines " ,mubaweb_df.shape)

number of lines  (14210, 42)

In [3]:
mubaweb_df["transaction_type"] = "Sale"
mubaweb_df["transaction_type"].value_counts()

transaction_type
Sale    14210
Name: count, dtype: int64

In [4]:
mubaweb_df["has_bathrooms"] = mubaweb_df["bathrooms"].notna()
mubaweb_df["has_heating"] = False

In [5]:
mubaweb_df.columns

Index(['listing_id', 'listing_url', 'source', 'title', 'property_type',
       'transaction_type', 'price', 'currency', 'price_type', 'surface_m2',
       'rooms', 'total_rooms', 'bedrooms', 'bathrooms', 'floor',
       'total_floors', 'country', 'governorate', 'city', 'district',
       'description', 'language', 'image_count', 'image_urls', 'date_posted',
       'last_updated', 'agency_name', 'seller_type', 'scrape_timestamp',
       'characteristics', 'has_ascenseur', 'has_cave', 'has_chauffage',
       'has_climatisation', 'has_jardin', 'has_meuble', 'has_parking',
       'has_piscine', 'has_securite', 'has_standing', 'has_terrasse',
       'has_vue_mer', 'has_bathrooms', 'has_heating'],
      dtype='object')

In [6]:
mubaweb_df = mubaweb_df.drop(columns=["price_type"])

In [7]:
mubaweb_df = mubaweb_df.drop(columns=["district"])

In [8]:
mubaweb_df = mubaweb_df.drop(columns=["language"])

In [9]:
mubaweb_df = mubaweb_df.drop(columns=["characteristics"])

In [10]:
mubaweb_df = mubaweb_df.drop(columns=["has_bathrooms"])

In [11]:
mubaweb_df.shape

(14210, 39)

In [12]:
mubaweb_df.rename(columns={
    "has_ascenceur": "has_elevator",
    "has_cave": "has_basement",
    "has_chauffage": "has_heating",
    "has_climatisation": "has_air_conditioning",
    "has_piscine": "has_pool",
    "has_vue_mer": "has_sea_view",
    "has_terrasse": "has_terrace",
    "has_jardin": "has_garden",
    "has_securite": "has_security",
    "has_meuble": "has_furniture",
    "has_ascenseur" : "has_elevator"
}, inplace=True)

In [13]:
# Get all CSV file paths
tayara_files = glob.glob("Data/raw_listings/tayara/*.csv")

# Read and combine them into one DataFrame
tayara_df = pd.concat(
    (pd.read_csv(file) for file in tayara_files),
    ignore_index=True
)

# Check the result
tayara_df.head()

,listing_id,title,price_numeric,currency,price_raw,category,city,governorate,location_raw,surface,...,criteria_chauffage_central,criteria_climatisation,criteria_parking,criteria_salles_de_bains,criteria_type_de_bien,criteria_type_de_transaction,image_urls,criteria_caméra_de_surveillance,criteria_celliers,criteria_parking_sous_sol
0,69777a69fea36ed612c9babe,Appartement S+3 – 3ᵉ étage | Résidence Omrane ...,389151.0,TND,389151 DT,immoneuf,Ghazela,Ariana,"Ghazela, Ariana",134.19,...,Chauffage central,Climatisation,Parking,2.0,Appartement,À Vendre,"[""https://cdn.tayara.tn/07/0767912b-4083-4d25-...",NaN,NaN,NaN
1,69723931fea36ed612c7631d,Une villa à Gammarth avec piscine,7000.0,TND,7000 DT,immobilier,Gammarth,Tunis,"Gammarth, Tunis",1.00,...,NaN,NaN,NaN,2.0,NaN,À Louer,"[""https://cdn.tayara.tn/fd/fda7ed24-ccdd-4ebb-...",NaN,NaN,NaN
2,6728f015981bc29b644499ac,Immeuble à louer lac 3,0.0,TND,NaN,immobilier,Le Kram,Tunis,"Le Kram, Tunis",3000.00,...,NaN,NaN,NaN,0.0,NaN,À Louer,"[""https://cdn.tayara.tn/32/32fbd00c-fec7-41e7-...",NaN,NaN,NaN
3,69396e358914daae519919c2,À vendre un terrain \nla marsa,0.0,TND,NaN,immobilier,La Marsa,Tunis,"La Marsa, Tunis",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,"[""https://cdn.tayara.tn/84/84e88214-f974-41d1-...",NaN,NaN,NaN
4,6973914bd921b01419d1c80a,À Louer – Espace Bureautique Haut Standing au ...,0.0,TND,NaN,immobilier,Lac 2,Tunis,"Lac 2, Tunis",550.00,...,NaN,NaN,NaN,NaN,NaN,À Louer,"[""https://cdn.tayara.tn/65/654c3c81-fc9d-4e82-...",NaN,NaN,NaN

In [14]:
tayara_df.shape

(21011, 27)

In [15]:
tayara_df["source"] = "tayara"
tayara_df["source"].value_counts()

source
tayara    21011
Name: count, dtype: int64

In [16]:
tayara_df.shape

(21011, 28)

In [17]:
tayara_df = tayara_df.drop(columns=["price_raw"])

In [18]:
tayara_df = tayara_df.drop(columns=["location_raw"])

In [19]:
tayara_df = tayara_df.drop(columns=["category"])

In [20]:
tayara_df = tayara_df.drop(columns=["criteria_celliers"])

In [21]:
tayara_df = tayara_df.drop(columns=["criteria_parking_sous_sol"])

In [22]:
tayara_df.shape

(21011, 23)

In [23]:
tayara_df["agency_name"] = ""
tayara_df["seller_type"] = ""

In [24]:
tayara_df.shape

(21011, 25)

In [25]:
tayara_df["country"] = "Tunisia"

In [26]:
tayara_df.shape

(21011, 26)

In [27]:
tayara_df.columns

Index(['listing_id', 'title', 'price_numeric', 'currency', 'city',
       'governorate', 'surface', 'bedrooms', 'description', 'date_posted',
       'image_count', 'listing_url', 'scraped_at', 'criteria_ascenseur',
       'criteria_chauffage_central', 'criteria_climatisation',
       'criteria_parking', 'criteria_salles_de_bains', 'criteria_type_de_bien',
       'criteria_type_de_transaction', 'image_urls',
       'criteria_caméra_de_surveillance', 'source', 'agency_name',
       'seller_type', 'country'],
      dtype='object')

In [28]:
mubaweb_df.columns

Index(['listing_id', 'listing_url', 'source', 'title', 'property_type',
       'transaction_type', 'price', 'currency', 'surface_m2', 'rooms',
       'total_rooms', 'bedrooms', 'bathrooms', 'floor', 'total_floors',
       'country', 'governorate', 'city', 'description', 'image_count',
       'image_urls', 'date_posted', 'last_updated', 'agency_name',
       'seller_type', 'scrape_timestamp', 'has_elevator', 'has_basement',
       'has_heating', 'has_air_conditioning', 'has_garden', 'has_furniture',
       'has_parking', 'has_pool', 'has_security', 'has_standing',
       'has_terrace', 'has_sea_view', 'has_heating'],
      dtype='object')

In [29]:
tayara_df.rename(columns={
    "surface": "surface_m2",
    "criteria_ascenseur": "has_elevator",
    "criteria_climatisation": "has_air_conditioning",
    "criteria_parking": "has_parking",
    "criteria_salles_de_bains": "has_bathrooms",
    "criteria_type_de_transaction": "transaction_type",
    "scraped_at": "scrape_timestamp",
    "price_numeric": "price",
    "criteria_caméra_de_surveillance" : "has_security",
    "criteria_type_de_transaction" : "transaction_type",
    "criteria_chauffage_central" : "has_heating" ,
    "criteria_type_de_bien" : "property_type"
}, inplace=True)

In [30]:
tayara_df["bathrooms"] = tayara_df["has_bathrooms"]

In [31]:
tayara_df = tayara_df.drop(columns=["has_bathrooms"])

In [32]:
# Get sets of columns
tayara_cols = set(tayara_df.columns)
mubaweb_cols = set(mubaweb_df.columns)

# All unique columns
all_cols = sorted(tayara_cols | mubaweb_cols)

# Prepare aligned DataFrame
comparison_list = []
for col in all_cols:
    tayara_val = col if col in tayara_cols else ""
    mubaweb_val = col if col in mubaweb_cols else ""
    comparison_list.append({"tayara_df": tayara_val, "mubaweb_df": mubaweb_val})

comparison_df = pd.DataFrame(comparison_list)
comparison_df

               tayara_df            mubaweb_df
0            agency_name           agency_name
1              bathrooms             bathrooms
2               bedrooms              bedrooms
3                   city                  city
4                country               country
5               currency              currency
6            date_posted           date_posted
7            description           description
8                                        floor
9            governorate           governorate
10  has_air_conditioning  has_air_conditioning
11                                has_basement
12          has_elevator          has_elevator
13                               has_furniture
14                                  has_garden
15           has_heating           has_heating
16           has_parking           has_parking
17                                    has_pool
18                                has_sea_view
19          has_security          has_security
20                                has_standing
21                                 has_terrace
22           image_count           image_count
23            image_urls            image_urls
24                                last_updated
25            listing_id            listing_id
26           listing_url           listing_url
27                 price                 price
28         property_type         property_type
29                                       rooms
30      scrape_timestamp      scrape_timestamp
31           seller_type           seller_type
32                source                source
33            surface_m2            surface_m2
34                 title                 title
35                                total_floors
36                                 total_rooms
37      transaction_type      transaction_type

In [33]:
import numpy as np

# Columns missing in tayara
missing_cols = set(mubaweb_df.columns) - set(tayara_df.columns)

for col in missing_cols:
    dtype = mubaweb_df[col].dtype

    # Boolean → set False
    if dtype == bool:
        tayara_df[col] = False

    # Numeric → use np.nan
    elif np.issubdtype(dtype, np.number):
        tayara_df[col] = np.nan

    # Everything else (object, string, category, etc.)
    else:
        tayara_df[col] = None

print("Added columns:", missing_cols)

Added columns: {'has_terrace', 'total_floors', 'has_sea_view', 'has_pool', 'has_basement', 'has_garden', 'total_rooms', 'has_standing', 'floor', 'has_furniture', 'last_updated', 'rooms'}

In [34]:
# Get sets of columns
tayara_cols = set(tayara_df.columns)
mubaweb_cols = set(mubaweb_df.columns)

# All unique columns
all_cols = sorted(tayara_cols | mubaweb_cols)

# Prepare aligned DataFrame
comparison_list = []
for col in all_cols:
    tayara_val = col if col in tayara_cols else ""
    mubaweb_val = col if col in mubaweb_cols else ""
    comparison_list.append({"tayara_df": tayara_val, "mubaweb_df": mubaweb_val})

comparison_df = pd.DataFrame(comparison_list)
comparison_df

               tayara_df            mubaweb_df
0            agency_name           agency_name
1              bathrooms             bathrooms
2               bedrooms              bedrooms
3                   city                  city
4                country               country
5               currency              currency
6            date_posted           date_posted
7            description           description
8                  floor                 floor
9            governorate           governorate
10  has_air_conditioning  has_air_conditioning
11          has_basement          has_basement
12          has_elevator          has_elevator
13         has_furniture         has_furniture
14            has_garden            has_garden
15           has_heating           has_heating
16           has_parking           has_parking
17              has_pool              has_pool
18          has_sea_view          has_sea_view
19          has_security          has_security
20          has_standing          has_standing
21           has_terrace           has_terrace
22           image_count           image_count
23            image_urls            image_urls
24          last_updated          last_updated
25            listing_id            listing_id
26           listing_url           listing_url
27                 price                 price
28         property_type         property_type
29                 rooms                 rooms
30      scrape_timestamp      scrape_timestamp
31           seller_type           seller_type
32                source                source
33            surface_m2            surface_m2
34                 title                 title
35          total_floors          total_floors
36           total_rooms           total_rooms
37      transaction_type      transaction_type

In [35]:
# ─────────────────────────────────────────────
# 1. Load all bigdatis CSV files
# ─────────────────────────────────────────────
bigdatis_files = glob.glob("DATA/raw_listings/big_datis/*.csv")

bigdatis_df = pd.concat(
    (pd.read_csv(file) for file in bigdatis_files),
    ignore_index=True
)

print("Shape after loading:", bigdatis_df.shape)
print(bigdatis_df.head())

# ─────────────────────────────────────────────
# 2. Drop columns not needed for the merge
# ─────────────────────────────────────────────
bigdatis_df = bigdatis_df.drop(columns=["price_type"])
bigdatis_df = bigdatis_df.drop(columns=["district"])
bigdatis_df = bigdatis_df.drop(columns=["language"])

# ─────────────────────────────────────────────
# 3. Rename columns to match the shared schema
# ─────────────────────────────────────────────
bigdatis_df.rename(columns={
    "id"                  : "listing_id",
    "link"                : "listing_url",
    "surface"             : "surface_m2",
    "number_of_rooms"     : "rooms",
    "number_of_salle_de_bain": "bathrooms",
    "total_floor"         : "total_floors",
    "image_url"           : "image_urls",
    "scraped_at"          : "scrape_timestamp",
    "has_ascenseur"       : "has_elevator",
    "has_cave"            : "has_basement",
    "has_chauffage"       : "has_heating",
    "has_climatisseur"    : "has_air_conditioning",
    "has_jardin"          : "has_garden",
    "has_meubles"         : "has_furniture",
    "has_piscine"         : "has_pool",
    "has_terrasse"        : "has_terrace",
    "has_vue_sur_mer"     : "has_sea_view",
}, inplace=True)

# ─────────────────────────────────────────────
# 4. Add missing columns (present in mubawab/tayara but not in bigdatis)
# ─────────────────────────────────────────────
bigdatis_df["country"]      = "Tunisia"
bigdatis_df["total_rooms"]  = None
bigdatis_df["last_updated"] = None
bigdatis_df["has_standing"] = False

# floor already exists in bigdatis, keep it as-is

# ─────────────────────────────────────────────
# 5. Normalize transaction_type to match the shared schema
#    (bigdatis uses "Vente" / "Location", others use "Sale" / "Rent")
# ─────────────────────────────────────────────
transaction_map = {
    "Vente"    : "Sale",
    "Location" : "Rent",
}
bigdatis_df["transaction_type"] = bigdatis_df["transaction_type"].map(
    lambda x: transaction_map.get(x, x)
)

# ─────────────────────────────────────────────
# 6. Verify final columns
# ─────────────────────────────────────────────
print("\nShape after treatment:", bigdatis_df.shape)
print("\nColumns:", bigdatis_df.columns.tolist())

# ─────────────────────────────────────────────
# 7. (Optional) Compare columns across the three datasets
#    Uncomment once mubaweb_df and tayara_df are also loaded
# ─────────────────────────────────────────────


# ─────────────────────────────────────────────
# Check for duplicates in each df
print("mubaweb duplicates:", mubaweb_df.columns[mubaweb_df.columns.duplicated()].tolist())
print("tayara duplicates: ", tayara_df.columns[tayara_df.columns.duplicated()].tolist())
print("bigdatis duplicates:", bigdatis_df.columns[bigdatis_df.columns.duplicated()].tolist())

# Remove duplicate columns (keeps the first occurrence)
mubaweb_df  = mubaweb_df.loc[:, ~mubaweb_df.columns.duplicated()]
tayara_df   = tayara_df.loc[:, ~tayara_df.columns.duplicated()]
bigdatis_df = bigdatis_df.loc[:, ~bigdatis_df.columns.duplicated()]

# Now merge
merged_df = pd.concat([mubaweb_df, tayara_df, bigdatis_df], ignore_index=True)
print("\nMerged shape:", merged_df.shape)

Shape after loading: (13868, 37)
        id                                           title  \
0  1203928            « A vendre appartement S1 sur plan »
1  1180444                      « tél appartement 405 m2 »
2  1184706  « Coquet studio à vendre à 140 MD à Hammamet »
3  1184528           « Appartement S+0 à vendre à Nabeul »
4  1233030         « S2 A vendre aux jardins de Carthage »

                                                link                source  \
0  https://bigdatis.tn/details/vente/el-mrezga/ap...               Mubawab
1  https://bigdatis.tn/details/vente/monastir-cen...                Tayara
2  https://bigdatis.tn/details/vente/hammamet-cen...                  Cava
3  https://bigdatis.tn/details/vente/nabeul/appar...               Fi Dari
4  https://bigdatis.tn/details/vente/jardins-de-c...  Facebook Marketplace

  property_type transaction_type     price currency price_type  surface  ...  \
0   Appartement            Vente  268000.0      TND       Fixe     57.0  ...
1   Appartement            Vente  450000.0      TND       Fixe    405.0  ...
2   Appartement            Vente  140000.0      TND       Fixe     40.0  ...
3   Appartement            Vente  140000.0      TND       Fixe     40.0  ...
4   Appartement            Vente  550000.0      TND       Fixe      NaN  ...

   has_chauffage  has_climatisseur  has_jardin  has_meubles  has_parking  \
0          False             False       False        False        False
1          False              True       False        False        False
2          False             False       False        False        False
3          False             False       False        False        False
4          False              True        True        False         True

  has_piscine has_security has_terrasse has_vue_sur_mer           scraped_at
0       False        False        False           False  2026-02-14 09:25:21
1       False        False         True           False  2026-02-14 09:25:35
2       False        False        False           False  2026-02-14 09:25:49
3       False        False        False           False  2026-02-14 09:26:02
4       False        False        False           False  2026-02-14 09:26:15

[5 rows x 37 columns]

Shape after treatment: (13868, 38)

Columns: ['listing_id', 'title', 'listing_url', 'source', 'property_type', 'transaction_type', 'price', 'currency', 'surface_m2', 'rooms', 'bathrooms', 'bedrooms', 'floor', 'total_floors', 'governorate', 'city', 'description', 'image_count', 'image_urls', 'date_posted', 'seller_type', 'agency_name', 'has_elevator', 'has_basement', 'has_heating', 'has_air_conditioning', 'has_garden', 'has_furniture', 'has_parking', 'has_pool', 'has_security', 'has_terrace', 'has_sea_view', 'scrape_timestamp', 'country', 'total_rooms', 'last_updated', 'has_standing']
mubaweb duplicates: ['has_heating']
tayara duplicates:  []
bigdatis duplicates: []

Merged shape: (49089, 38)

C:\Users\mohameddkhalil\AppData\Local\Temp\ipykernel_6644\410719443.py:90: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  merged_df = pd.concat([mubaweb_df, tayara_df, bigdatis_df], ignore_index=True)